---
- import_playbook: playbooks/appimage-launcher.yml
- import_playbook: playbooks/dev.yml
- import_playbook: playbooks/terminal.yml
- import_playbook: playbooks/browsers.yml
- import_playbook: playbooks/spotify.yml
- import_playbook: playbooks/tailscale.yml
